name: Rolling Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      draft:
        description: "Create draft release"
        required: false
        default: true
        type: boolean

jobs:
  rolling:
    name: Rolling Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          run_install: false

      - name: Build Pre-release
        run: |
          chmod +x build.sh
          ./build.sh --dev --compress --skip-i18n
        env:
          CROWDIN_PROJECT_ID: ""
          CROWDIN_PERSONAL_TOKEN: ""
          OPENLIST_FRONTEND_BUILD_MODE: dev
          OPENLIST_FRONTEND_BUILD_COMPRESS: true

      - name: Read version and determine tag name
        id: version
        run: |
          version=$(cat dist/VERSION)
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "tag_name=rolling" >> $GITHUB_OUTPUT

      - name: Remove the existing pre-release
        run: gh release delete ${{ steps.version.outputs.tag_name }} --cleanup-tag --yes || true
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Publish pre-release on GitHub
        run: |
          gh release create \
            --title "Pre-release ${{ steps.version.outputs.version }}" \
            --notes "Pre-release build for ${{ steps.version.outputs.version }}\nThis is a development build and not intended for production use." \
            --prerelease \
            --draft=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.draft || false }} \
            ${{ steps.version.outputs.tag_name }} \
            dist/openlist-frontend-dist-v*-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ github.token }}
