name: Format

on:
  push:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: pnpm install

      - name: Format
        run: pnpm run format

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "[skip ci] style: format code with prettier"
          commit_author: "GitHub Actions <actions@github.com>"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
